wheel:
	PYTHONPATH=.. python3 steering_wheel.py && ../docs/render /dev/shm/steering_wheel.stl steering_wheel.png
top:
	PYTHONPATH=.. python3 spinning_top.py && ../docs/render spinning_top.stl spinning_top.png
pillar:
	PYTHONPATH=.. python3 pillar.py && ../docs/render /dev/shm/pillar.stl pillar.png
